---
- name: "Check for postgresql_exporter binary"
  stat:
    path: "/usr/local/bin/postgres_exporter"
  changed_when: false
  register: postgresql_exporter_install

- when: not postgresql_exporter_install.stat.exists
  block:
    - name: "Download postgresql_exporter..."
      get_url:
        url: '{{ postgresql_exporter_url }}'
        dest: /tmp/
        timeout: 120

    - name: "Extract archive"
      unarchive:
        src: "/tmp/{{ postgresql_exporter_tgz }}"
        dest: "/usr/local/bin/"
        extra_opts: [--strip-components=1]
        remote_src: true
        mode: 0644

- name: "Create systemd for postgresql_exporter"
  template:
    src: postgresql_exporter.service.j2
    dest: /etc/systemd/system/postgresql_exporter.service
    mode: 0644
  notify: "restart postgresql_exporter"

- name: "Start postgresql_exporter.service"
  systemd:
    name: postgresql_exporter
    state: started
    enabled: true
    daemon_reload: true
