---
- name: Prepare
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Start dbus for oraclelinux9
      ansible.builtin.systemd:
        name: dbus
        state: started
        enabled: true
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "9"

  tasks:
    - name: "create postgresql_exporter group"
      ansible.builtin.group:
        name: postgres

    - name: "Create postgresql_exporter user"
      ansible.builtin.user:
        name: postgres
        group: postgres
        system: true
